package de.lucawimmer.cloudinventory.storage;

import com.google.common.io.ByteArrayDataOutput;
import com.google.common.io.ByteStreams;
import de.lucawimmer.cloudinventory.CloudInventory;
import de.lucawimmer.cloudinventory.objects.ServerInfo;
import org.bukkit.Bukkit;
import org.bukkit.craftbukkit.libs.com.google.gson.Gson;
import org.bukkit.scheduler.BukkitRunnable;
import org.json.simple.JSONObject;

import java.io.DataOutputStream;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.SocketAddress;
import java.util.HashMap;
import java.util.Iterator;

public class PufferStorage {
    public static HashMap<String, String> playerQueue = new HashMap<String, String>();
    private static HashMap<String, String> waitingConnections = new HashMap<String, String>();

    public static void addConnectingPlayer(String p, String s) {
        if(!hasConnectingPlayer(p)) waitingConnections.put(p, s);
    }

    public static void removeConnectingPlayer(String p) {
        if(hasConnectingPlayer(p)) waitingConnections.remove(p);
    }

    public static void addQueuedPlayer(String p, String s) {
        if(!hasQueuedPlayer(p)) playerQueue.put(p, s);
    }

    public static void removeQueuedPlayer(String p) {
        if(hasQueuedPlayer(p)) playerQueue.remove(p);
    }


    public static boolean hasConnectingPlayer(String p) {
        if (waitingConnections.containsKey(p))
            return true;

        return false;
    }

    public static boolean hasQueuedPlayer(String p) {
        if (playerQueue.containsKey(p))
            return true;

        return false;
    }

    public static void pufferClientProccessing() {
        Bukkit.getLogger().info("Starting pufferClientProcessing Task");
        Bukkit.getScheduler().scheduleSyncRepeatingTask(CloudInventory.getInstance(), new Runnable() {

            @Override
            public void run() {
                Iterator<String> it = waitingConnections.keySet().iterator();
                while (it.hasNext()) {
                    String s = it.next();
                    if (Bukkit.getPlayer(s) != null) {
                        final String dest = waitingConnections.get(s);
                        it.remove();
                        initiateTeleport(s, dest);
                    }
                }

                Iterator<String> itp = playerQueue.keySet().iterator();
                while (itp.hasNext()) {
                    String s = itp.next();
                    if (Bukkit.getPlayer(s) != null) {
                        String json = playerQueue.get(s);
                        itp.remove();
                        try {
                            initiatePackets(s, json);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }
                }

            }
        }, 10L, 1L);
    }

    private static void initiatePackets(String p, String s) throws IOException {
        // TO SERVER
        ServerInfo playerinfo = new Gson().fromJson(s, ServerInfo.class);
        String ip = playerinfo.getServer().split(":")[0];
        Integer port = Integer.parseInt(playerinfo.getServer().split(":")[1]);
        String password = playerinfo.getOwnpassword();
        JSONObject json = new JSONObject();
        json.put("header", "server; transfer;");
        json.put("password", password);
        json.put("server", Bukkit.getServer().getIp() + ":" + CloudInventory.getDefaultConfig().getInt("port"));
        json.put("player", playerinfo.getPlayer());
        json.put("destination", playerinfo.getDestination());
        SocketAddress address = new InetSocketAddress(ip, port);
        Socket clientSocket = new Socket();
        clientSocket.connect(address, 20000);
        DataOutputStream outToServer = new DataOutputStream(clientSocket.getOutputStream());
        outToServer.writeBytes(json.toString());
        clientSocket.close();
        Bukkit.getLogger().info("Packet generated by " + playerinfo.getPlayer() + " has been sent to destination server.");
        PufferStorage.addConnectingPlayer(playerinfo.getPlayer(), playerinfo.getDestination());
    }

    private static void initiateTeleport(final String p, final String dest) {
        if (Bukkit.getPlayer(p) != null) {
            Bukkit.getServer().getScheduler().scheduleAsyncDelayedTask(CloudInventory.getInstance(), new Runnable() {
                @Override
                public void run() {

                    new BukkitRunnable() {
                        int seconds = 5;

                        public void run() {

                            if (seconds > -1) {
                                switch (seconds) {
                                    case 5:
                                        if (Bukkit.getPlayer(p) != null) Bukkit.getPlayer(p).sendMessage("§7[§6H§7] §fDu wirst in 5 Sekunden teleportiert.");
                                        seconds--;
                                        break;
                                    case 4:
                                        if (Bukkit.getPlayer(p) != null)  Bukkit.getPlayer(p).sendMessage("§7[§6H§7] §fDu wirst in 4 Sekunden teleportiert.");
                                        seconds--;
                                        break;
                                    case 3:
                                        if (Bukkit.getPlayer(p) != null)  Bukkit.getPlayer(p).sendMessage("§7[§6H§7] §fDu wirst in 3 Sekunden teleportiert.");
                                        seconds--;
                                        break;
                                    case 2:
                                        if (Bukkit.getPlayer(p) != null)  Bukkit.getPlayer(p).sendMessage("§7[§6H§7] §fDu wirst in 2 Sekunden teleportiert.");
                                        seconds--;
                                        break;
                                    case 1:
                                        if (Bukkit.getPlayer(p) != null) Bukkit.getPlayer(p).sendMessage("§7[§6H§7] §fDu wirst in 1 Sekunden teleportiert.");
                                        seconds--;
                                        break;
                                    case 0:
                                        try {
                                            final ByteArrayDataOutput out = ByteStreams.newDataOutput();
                                            out.writeUTF("Connect");
                                            if (dest != null) {
                                                if (!dest.equals("default")) {
                                                    out.writeUTF(dest);
                                                } else {
                                                    out.writeUTF(CloudInventory.getDefaultConfig().getString("default-forward-server"));
                                                }
                                                Bukkit.getPlayer(p).sendPluginMessage((CloudInventory.getInstance()), "BungeeCord", out.toByteArray());
                                            }
                                        } catch (Exception e) {
                                            e.printStackTrace();
                                        }
                                        cancel();
                                        break;
                                }
                            } else {
                                cancel();
                            }
                        }
                    }.runTaskTimer(CloudInventory.getInstance(), 0, 20);
                }
            }, 20L * 4);
        }
    }
}
